### ISSUE TITLE
Discrete models fitting available only with HN?

### ISSUE THREAD

**Issue by PushkarevAS** [jdhuang-csm/hybrid-drt#3]
Hello!

It seems like currently the discrete models could be fitted only with HN elements.

Is there any way to apply other basic elements like RC, RQ or ZARC?

BR
Artem Pushkarev

**Comment by jdhuang-csm** [comment]
Hello!

The discrete element models can be fitted with most basic circuit elements including RC, RQ (ZARC), and HN, as well as ohmic resistors, inductors, capacitors, and CPEs. However, the fast optimization enabled by analytical Jacobian/Hessian computation is not yet implemented for RC and RQ elements (you can still fit these models, it just won't be quite as fast as for HN models).

If you want to make a discrete model from scratch, you can just write the elements that you want in the circuit string, e.g.:
`dem = DiscreteElementModel('R0-L0-RQ1-RC2-HN3`)
for a model with an ohmic resistor, an inductor, an RQ element, an RC element, and an HN element.

If you want to convert a fitted DRT instance to a discrete element model, you can also specify a customized circuit. For example, to treat all DRT peaks as RQ elements:
`dem = DiscreteElementModel.from_drt(drt, x_raw=drt.qphb_history[-1]['x'], model_string='R0-L0-{DRT}', drt_element='RQ')`

Alternatively, to specify a different element type for each peak (in this case, RQ for the 1st peak, RC for the 2nd, and HN for the 3rd:
`dem = DiscreteElementModel.from_drt(drt, x_raw=drt.qphb_history[-1]['x'], peak_indices=[10, 20, 30], model_string='R0-L0-RQ1-RC2-HN3')`
If you use this approach, it's probably best to specify the indices of the peaks as shown above to ensure that the selected peaks match the specified elements. Circuit elements are ordered from shortest timescale (highest frequency) to longest timescale (lowest frequency). You can get peak indices by using `drt.find_peaks(*args, **kwargs, return_info=True)`.

I do apologize for the lack of documentation, and I hope to improve it soon.

**Comment by PushkarevAS** [comment]
Dear Jake,

Thank you very much for quick response!

I got your point.

I am mostly following your tutorial, so I need to perform the Dual fit with further calculation of the optimized discrete model. Is it possible to do Dual fit with models based on the RQ as you mentioned above?

If I try it this way:

dual.dual_fit_eis(freq_exp2, Z_exp2, nonneg=True, solve_rp=True, update_scale=True,
                  generate_kw=dict(find_peaks_kw=dict(prominence=1e-3)), discrete_kw=dict(model_init_kw=dict(model_string='R0-L0-{DRT}', drt_element='RQ')))

I get the following: 

  File ~\*********\hybrid-drt-main\hybdrt\models\elements.py:1960 in element_f_jacobian
    return jac
UnboundLocalError: cannot access local variable 'jac' where it is not associated with a value

Sorry, I am very new to python and coding....

Thank you in advance!

BR
Artem Pushkarev

**Comment by jdhuang-csm** [comment]
That is almost exactly right, but you need to add one more argument (`jac='2-point'`)to the discrete_kw dict to use the RQ element:

`discrete_kw=dict(model_init_kw=dict(model_string='R0-L0-{DRT}', drt_element='RQ', jac='2-point')`

This is only necessary because the RQ element isn't fully supported yet. I will keep this issue open until I implement the analytical Jacobian/Hessian calculations for RC and RQ elements. Once that is implemented, you should be able to remove the `jac` argument, but for now you will need it.

**Comment by jdhuang-csm** [comment]
Actually, I think that you will hit another error when the model attempts to evaluate plausibility metrics with the RQ elements. So, I will need to finish the implementation for this to work. I will try to get to it this week.

**Comment by jdhuang-csm** [comment]
This should be fixed now. If you want to use RQ or RC elements instead of HN elements in dual_fit, you can just write the following:
`dual.dual_fit_eis(freq, z, discrete_kw={'model_init_kw':{'drt_element': element_type}})`
where `element_type` is one of `'RC'`, `'RQ',` or `'HN'`. You should NOT specify `jac='2-point'` (this was just a temporary workaround). Please give it a try and let me know if it works for you.

**Comment by PushkarevAS** [comment]
Hello!

I was tried the updated version, but faced with the issue with the scipy, so the following error appears in the very beginning:

ImportError: cannot import name 'cumtrapz' from 'scipy.integrate' (C:\Users\Pushk\anaconda3\envs\hybdrt2024\Lib\site-packages\scipy\integrate\__init__.py)

It doesn't work with latest (1.14) version of scipy, it seems like they modify their functions (no function called "cumtrapz"). Honestly, I struggled to use older versions (1.5 and lower,  having 'cumtrapz') in my environment for Hybrid DRT (which is made according to instructions with python 3.12). So, probably you can check if the environment is valid for your recent improvements.

Thank you very much in advance!

BR
Artem

**Comment by jdhuang-csm** [comment]
Thanks, I didn't realize that cumtrapz had been removed in the latest version of scipy. The latest push should fix the issue.

**Comment by PushkarevAS** [comment]
Next minor issue:
 File ~\anaconda3\envs\hybdrt2024\Lib\site-packages\sklearn\utils\fixes.py:113
    _sparse_linalg_cg = scipy.sparse.linalg.cg

AttributeError: module 'scipy.sparse' has no attribute 'linalg'

**Comment by jdhuang-csm** [comment]
This seems to be a conflict between the versions of sklearn and scipy that you have installed. How did you create the environment? If you use conda to create the environment from the latest hybdrt.yml file, this should not occur (see the installation.txt file for instructions).

I also made a couple more fixes for missing packages and broken imports due to version changes, so you should re-download the package, but that is unrelated to this issue.

**Comment by jdhuang-csm** [comment]
Closing this since the original issue is fixed. The environment creation from the yml file seems to work properly on my end, but please feel free to open a new issue if you are still encountering errors.
